# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors
# Copyright (c) 2022 Embedded and Real-Time Systems Laboratory,
#                    Graduate School of Information Science, Nagoya Univ., JAPAN

PBIO_PLATFORM = prime_hub_spike-rt
PB_MCU_SERIES = F4
PB_CMSIS_MCU = STM32F413xx
PB_MCU_EXT_OSC_HZ = 16000000
PB_USE_HAL = 1
PB_USE_LSM6DS3TR_C = 1
PB_LIB_BLUENRG = 0
PB_LIB_BTSTACK = 1
PB_LIB_STM32_USB_DEVICE = 1

include ./make.mk
